export const solutions = [
  {
    slug: "ai-automation",
    title: "AI Automation",
    tagline: "Cut the manual work. Keep the quality.",
    icon: "⬡",
    description: "We help organisations stop spending time on repetitive tasks. Our automation systems handle document processing, approvals, data entry and routing so your team can focus on work that actually needs them.",
    capabilities: ["Document reading and data extraction", "Workflow routing and approvals", "Multi-system data synchronisation", "Automated reporting and alerts", "Human review for edge cases", "Process monitoring and analytics"],
    technologies: ["Python", "Apache Airflow", "OpenAI", "LangChain", "Kubernetes", "PostgreSQL"],
    industries: ["Finance", "Healthcare", "Legal", "Logistics"],
    benefits: [{ metric: "70%", label: "Less time spent on manual tasks" }, { metric: "99.2%", label: "Data extraction accuracy" }, { metric: "3x", label: "Throughput increase" }],
  },
  {
    slug: "ai-agents",
    title: "AI Agents",
    tagline: "AI that works on its own, around the clock.",
    icon: "◈",
    description: "Our AI agents can plan, reason and take action across your systems without needing someone to hold their hand. They handle complex tasks end to end, escalating only when human judgment is genuinely needed.",
    capabilities: ["Multi-agent task coordination", "Tool use and API integration", "Memory and context between sessions", "Goal planning and execution", "Live monitoring and control", "Custom agent training for your domain"],
    technologies: ["LangGraph", "AutoGen", "OpenAI", "Claude API", "Redis", "PostgreSQL"],
    industries: ["Technology", "Finance", "E-Commerce"],
    benefits: [{ metric: "24/7", label: "Autonomous operation" }, { metric: "85%", label: "Tasks completed without review" }, { metric: "60%", label: "Cost savings vs manual teams" }],
  },
  {
    slug: "enterprise-software",
    title: "Enterprise Software",
    tagline: "Software that lasts and scales.",
    icon: "▣",
    description: "We build software for organisations that need things to work reliably over the long term. No shortcuts, no duct tape. Just well-architected systems that hold up under real operational pressure.",
    capabilities: ["Full-stack application development", "Microservices and API design", "Database architecture", "Legacy system modernisation", "Cloud deployment and DevOps", "Performance and security hardening"],
    technologies: ["Next.js", "Node.js", "Go", "PostgreSQL", "AWS", "Docker"],
    industries: ["Government", "Finance", "Healthcare", "Technology"],
    benefits: [{ metric: "99.99%", label: "Uptime achieved for clients" }, { metric: "5x", label: "Faster release cycles" }, { metric: "40%", label: "Infrastructure cost reduction" }],
  },
  {
    slug: "data-intelligence",
    title: "Data Intelligence",
    tagline: "Your data should answer questions, not create them.",
    icon: "◉",
    description: "We build data systems that actually make sense of your information. Pipelines that run reliably, dashboards that tell you what matters, and models that help you make better decisions faster.",
    capabilities: ["Data warehouse design", "Real-time analytics pipelines", "Business intelligence dashboards", "Forecasting and predictive models", "Data quality and governance", "Self-service reporting tools"],
    technologies: ["dbt", "Snowflake", "Apache Kafka", "Databricks", "Tableau", "Metabase"],
    industries: ["Finance", "Healthcare", "E-Commerce", "Logistics"],
    benefits: [{ metric: "10x", label: "Faster insight generation" }, { metric: "98%", label: "Pipeline reliability" }, { metric: "60%", label: "Less time on reporting" }],
  },
  {
    slug: "compliance-systems",
    title: "Compliance Systems",
    tagline: "Stay on the right side of every regulation.",
    icon: "⬟",
    description: "Compliance work is getting harder and more expensive every year. We build systems that monitor, track and report on your regulatory obligations automatically, so your team spends less time on checklists and more time on strategy.",
    capabilities: ["Regulatory monitoring and alerts", "Audit trail management", "KYC and AML workflow automation", "GDPR and data privacy tools", "Risk scoring and reporting", "Regulatory change tracking"],
    technologies: ["Python", "Elasticsearch", "PostgreSQL", "Apache Kafka", "AWS GovCloud", "Vault"],
    industries: ["Finance", "Legal", "Healthcare", "Government"],
    benefits: [{ metric: "90%", label: "Less compliance review time" }, { metric: "Zero", label: "Regulatory violations post-launch" }, { metric: "75%", label: "Audit preparation time saved" }],
  },
  {
    slug: "cloud-infrastructure",
    title: "Cloud Infrastructure",
    tagline: "Infrastructure that runs quietly and costs less.",
    icon: "◻",
    description: "We design and manage cloud environments built for AI workloads, high availability and global scale. Whether you are migrating, modernising or building from scratch, we make sure the foundation is solid.",
    capabilities: ["Multi-cloud and hybrid architecture", "Infrastructure as code", "AI and ML compute management", "Security hardening and compliance", "Cost optimisation and FinOps", "Disaster recovery planning"],
    technologies: ["AWS", "GCP", "Azure", "Terraform", "Kubernetes", "Prometheus"],
    industries: ["Technology", "Finance", "Healthcare", "Government"],
    benefits: [{ metric: "40%", label: "Average infrastructure cost reduction" }, { metric: "99.99%", label: "Uptime achieved" }, { metric: "10x", label: "Faster deployment frequency" }],
  },
  {
    slug: "digital-transformation",
    title: "Digital Transformation",
    tagline: "Modernisation that actually sticks.",
    icon: "◆",
    description: "Most transformation programmes fail because they focus on technology and forget about people. We work with your teams from day one to make sure the change lands properly and delivers lasting results.",
    capabilities: ["Technology readiness assessment", "Roadmap and architecture planning", "Change management programmes", "Legacy migration strategy", "Vendor and platform selection", "Enterprise architecture consulting"],
    technologies: ["AWS", "Azure", "SAP", "Salesforce", "ServiceNow", "MuleSoft"],
    industries: ["Finance", "Healthcare", "Government", "Logistics", "Real Estate"],
    benefits: [{ metric: "2.5x", label: "ROI on transformation programmes" }, { metric: "83%", label: "Employee adoption rate" }, { metric: "18mo", label: "Average time to measurable impact" }],
  },
];

export const industries = [
  {
    slug: "finance",
    image: "https://images.pexels.com/photos/534216/pexels-photo-534216.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Financial Services",
    subtitle: "Built for the demands of a regulated industry.",
    description: "Financial institutions deal with enormous complexity every day. Regulatory pressure, real-time transaction requirements, fraud risk and the expectation of zero downtime. We have built systems for organisations in this space and we understand what is at stake.",
    challenges: ["Growing compliance burden across multiple jurisdictions", "Fraud detection that needs to work in real time", "Data sitting in silos across different business units", "Manual reporting consuming analyst capacity", "Legacy systems slowing down digital products"],
    solutions: ["Automated KYC and AML workflows", "Real-time fraud scoring and transaction monitoring", "Unified data platforms across business units", "Regulatory reporting automation", "Core banking modernisation and API layers"],
    stats: [{ metric: "99.8%", label: "Fraud detection accuracy" }, { metric: "$2.1B+", label: "Transactions processed daily" }, { metric: "85%", label: "Compliance review time reduced" }],
  },
  {
    slug: "healthcare",
    image: "https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Healthcare",
    subtitle: "Technology that serves patients as much as staff.",
    description: "Healthcare organisations need technology that is both innovative and rigorously safe. Every system we build for this sector is designed around clinical requirements, data privacy and regulatory compliance. Patient outcomes come first.",
    challenges: ["Documentation burden reducing time with patients", "HIPAA compliance across complex data ecosystems", "Poor interoperability between legacy systems", "Diagnostic support and triage at scale", "Revenue cycle inefficiency and claims errors"],
    solutions: ["Clinical documentation AI and ambient transcription", "HIPAA compliant data infrastructure", "Healthcare interoperability using HL7 FHIR", "AI assisted clinical decision support", "Automated revenue cycle management"],
    stats: [{ metric: "40%", label: "Reduction in documentation time" }, { metric: "100%", label: "HIPAA compliance maintained" }, { metric: "3x", label: "Faster claims processing" }],
  },
  {
    slug: "legal",
    image: "https://images.pexels.com/photos/5669619/pexels-photo-5669619.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Legal Services",
    subtitle: "AI that works alongside attorneys, not instead of them.",
    description: "Legal work demands precision. We build tools that help law firms and legal teams handle large document volumes, speed up research and manage contracts without cutting corners on accuracy.",
    challenges: ["Document review and due diligence taking weeks", "Research time eating into billable capacity", "Contract management across large portfolios", "Knowledge that walks out the door with people", "Client reporting taking too long"],
    solutions: ["AI powered contract analysis and review", "Legal research with citation verification", "Contract lifecycle management systems", "Knowledge base and precedent search", "Matter management and client dashboards"],
    stats: [{ metric: "75%", label: "Reduction in document review time" }, { metric: "10x", label: "Research throughput increase" }, { metric: "$180K", label: "Annual savings per attorney" }],
  },
  {
    slug: "logistics",
    image: "https://images.pexels.com/photos/1427541/pexels-photo-1427541.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Logistics and Supply Chain",
    subtitle: "Intelligence for operations that never stop.",
    description: "Global supply chains run at a pace that leaves no room for guesswork. We build the intelligence layer that helps logistics organisations forecast demand, optimise routes and keep goods moving reliably.",
    challenges: ["Demand forecasting accuracy and inventory costs", "Last mile delivery efficiency", "Supplier visibility and risk exposure", "Customs and cross border compliance", "Warehouse operations and labour planning"],
    solutions: ["AI powered demand forecasting", "Route optimisation systems", "Supplier risk monitoring", "Customs documentation automation", "Warehouse management and robotics integration"],
    stats: [{ metric: "23%", label: "Inventory cost reduction" }, { metric: "15%", label: "Delivery efficiency improvement" }, { metric: "99.1%", label: "On time delivery rate" }],
  },
  {
    slug: "real-estate",
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Real Estate",
    subtitle: "Smarter tools for asset heavy organisations.",
    description: "Real estate organisations manage complex portfolios, high volume transactions and a lot of stakeholder relationships. We build platforms that bring clarity to every stage of the property lifecycle.",
    challenges: ["Property valuation accuracy", "Transaction and document management", "Tenant experience and service delivery", "Portfolio performance reporting", "Compliance across multiple jurisdictions"],
    solutions: ["AI powered property valuation and market analytics", "Transaction management and document automation", "Tenant experience portals", "Portfolio management dashboards", "Compliance monitoring systems"],
    stats: [{ metric: "94%", label: "Valuation model accuracy" }, { metric: "60%", label: "Faster transaction processing" }, { metric: "4.8/5", label: "Tenant satisfaction score" }],
  },
  {
    slug: "government",
    image: "https://images.pexels.com/photos/1550337/pexels-photo-1550337.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Government and Public Sector",
    subtitle: "Systems that serve the public well.",
    description: "Government agencies operate under unique constraints. Security requirements, public accountability and the need to serve everyone fairly. We build systems that meet these requirements without sacrificing usability.",
    challenges: ["Legacy infrastructure that is hard to replace", "Citizen services that need to work at scale", "Security and data sovereignty requirements", "Cross agency collaboration and data sharing", "Procurement and delivery complexity"],
    solutions: ["Secure cloud modernisation with compliance built in", "Citizen portal development", "Identity and access management", "Interagency data sharing platforms", "AI powered service routing and support"],
    stats: [{ metric: "99.99%", label: "System uptime achieved" }, { metric: "5M+", label: "Citizens served via our systems" }, { metric: "70%", label: "Faster permit and service processing" }],
  },
  {
    slug: "education",
    image: "https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Education",
    subtitle: "Technology that helps institutions focus on learning.",
    description: "Universities, schools and training organisations carry a growing administrative burden that pulls resources away from teaching and student support. We build systems that automate the operational side so educators can spend more time on what actually matters.",
    challenges: ["Student data scattered across disconnected systems", "Admissions and enrolment processes that are slow and manual", "Difficulty identifying students who are at risk of falling behind", "Reporting and compliance requirements consuming staff time", "Inconsistent digital experience across departments"],
    solutions: ["Unified student information platforms", "AI powered admissions screening and processing", "Early warning systems for student performance", "Automated regulatory reporting and accreditation tools", "Learning management system integration and analytics"],
    stats: [{ metric: "50%", label: "Reduction in admissions processing time" }, { metric: "3x", label: "Faster student support response" }, { metric: "90%", label: "Improvement in data accuracy across systems" }],
  },
  {
    slug: "insurance",
    image: "https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Insurance",
    subtitle: "Faster decisions. Lower risk. Better customer experience.",
    description: "Insurance companies deal with enormous volumes of documents, claims and customer interactions every day. The ones winning right now are the ones using AI to process faster, detect fraud earlier and serve customers without making them wait.",
    challenges: ["Claims processing that takes days or weeks", "Fraud detection relying on manual review", "Underwriting that is slow and inconsistent", "Customer service queues overwhelming support teams", "Policy documents and data living in too many places"],
    solutions: ["Automated claims intake and triage", "AI powered fraud detection and scoring", "Intelligent underwriting support tools", "AI customer service and query resolution", "Unified policy and document management"],
    stats: [{ metric: "65%", label: "Faster claims processing" }, { metric: "80%", label: "Reduction in fraudulent claims missed" }, { metric: "4.6/5", label: "Customer satisfaction improvement" }],
  },
  {
    slug: "manufacturing",
    image: "https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Manufacturing",
    subtitle: "AI that keeps production lines moving.",
    description: "Manufacturing organisations face pressure from every direction. Rising input costs, tighter margins, supply chain volatility and increasing customer expectations. AI gives manufacturers the visibility and automation they need to stay competitive.",
    challenges: ["Unplanned downtime disrupting production schedules", "Quality control relying too heavily on manual inspection", "Supply chain visibility gaps causing delays", "Energy costs rising without clear optimisation path", "Skilled labour shortages and knowledge retention"],
    solutions: ["Predictive maintenance and equipment monitoring", "Computer vision quality inspection systems", "Supply chain visibility and risk platforms", "Energy usage optimisation and monitoring", "Digital knowledge capture and training tools"],
    stats: [{ metric: "35%", label: "Reduction in unplanned downtime" }, { metric: "28%", label: "Improvement in quality control accuracy" }, { metric: "20%", label: "Energy cost reduction" }],
  },
  {
    slug: "retail",
    image: "https://images.pexels.com/photos/5632388/pexels-photo-5632388.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Retail and E-Commerce",
    subtitle: "Smarter operations behind every sale.",
    description: "Retail and e-commerce businesses move fast. Customer expectations are high, margins are tight and the competition never stops. We help retailers use AI to personalise better, stock smarter and run leaner operations without sacrificing the customer experience.",
    challenges: ["Inventory forecasting that leads to overstock and stockouts", "Customer personalisation at scale", "Returns management consuming too many resources", "Fraud in online transactions and payments", "Disconnected data between online and physical channels"],
    solutions: ["AI powered inventory and demand forecasting", "Personalisation engines for product and content", "Automated returns processing and fraud detection", "Unified customer data platforms", "Operational analytics and margin optimisation"],
    stats: [{ metric: "31%", label: "Reduction in stockout events" }, { metric: "22%", label: "Increase in average order value" }, { metric: "45%", label: "Faster returns processing" }],
  },
];

export const caseStudies = [
  {
    slug: "meridian-bank-compliance",
    image: "https://images.pexels.com/photos/50987/money-card-business-credit-card-50987.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Meridian Financial Group",
    industry: "Financial Services",
    title: "Rebuilding Compliance for a Global Bank",
    summary: "A global bank with $340 billion in assets needed to overhaul its compliance systems after regulators identified serious gaps in how it monitored transactions.",
    challenge: "Meridian's compliance team was using a mix of old tools, spreadsheets and manual reviews to manage obligations across 14 countries. When regulators examined them, they found it was taking up to 48 hours to flag suspicious transactions. That was not good enough.",
    solution: "We designed and built a compliance intelligence platform that monitors every transaction in real time, generates suspicious activity reports automatically and keeps a clean audit trail of everything. We connected it to their existing core banking system through a custom API layer, so nothing had to be ripped out.",
    outcomes: [{ metric: "2 hrs", label: "Average detection time, down from 48 hours" }, { metric: "91%", label: "Reduction in manual compliance tasks" }, { metric: "$4.2M", label: "Annual operational savings" }, { metric: "Zero", label: "Regulatory findings in follow up examinations" }],
    technologies: ["Python", "Apache Kafka", "Elasticsearch", "PostgreSQL", "AWS GovCloud"],
    duration: "14 months",
  },
  {
    slug: "atlas-health-documentation",
    image: "https://images.pexels.com/photos/305568/pexels-photo-305568.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Atlas Health Network",
    industry: "Healthcare",
    title: "Giving Doctors Their Time Back",
    summary: "A regional health network with 47 hospitals deployed ambient AI documentation across its physician workforce and recovered thousands of hours of clinical capacity.",
    challenge: "Physicians at Atlas were spending over three hours per shift on documentation. That is time taken directly away from patients. Burnout was rising and the quality of notes was inconsistent, which was causing billing errors downstream.",
    solution: "We built a system that listens to physician patient conversations, generates structured clinical notes automatically and pushes them into their Epic records for review. Doctors check and approve, but they are not starting from scratch every time.",
    outcomes: [{ metric: "2.1 hrs", label: "Documentation time saved per physician per shift" }, { metric: "98.7%", label: "Documentation accuracy rate" }, { metric: "$28M", label: "Annual capacity value recovered" }, { metric: "4.7/5", label: "Physician satisfaction score" }],
    technologies: ["Whisper API", "GPT-4", "HL7 FHIR", "React", "AWS HIPAA"],
    duration: "8 months",
  },
  {
    slug: "nexus-logistics-forecasting",
    image: "https://images.pexels.com/photos/1427541/pexels-photo-1427541.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Nexus Global Logistics",
    industry: "Logistics",
    title: "Smarter Inventory Across 180 Distribution Centres",
    summary: "One of the world's largest logistics operators deployed AI forecasting that cut inventory holding costs by 23 percent while improving fulfilment rates.",
    challenge: "Nexus was making inventory decisions based on data that was 90 days old. They had 180 distribution centres and 3,400 clients. Overstock and stockouts were costing them $180 million a year.",
    solution: "We built a demand intelligence platform that pulls in over 240 signals including weather, economic data and client order history and updates inventory recommendations every four hours. Distribution managers see what they need to order before they run out.",
    outcomes: [{ metric: "23%", label: "Inventory cost reduction" }, { metric: "99.1%", label: "Order fulfilment rate" }, { metric: "$41M", label: "First year savings" }, { metric: "4 hours", label: "Forecast update frequency, down from 90 days" }],
    technologies: ["Python", "XGBoost", "Apache Kafka", "Snowflake", "dbt", "Kubernetes"],
    duration: "11 months",
  },
  {
    slug: "caldwell-legal-platform",
    image: "https://images.pexels.com/photos/5668882/pexels-photo-5668882.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Caldwell and Reyes LLP",
    industry: "Legal Services",
    title: "Faster Due Diligence for a 600 Attorney Firm",
    summary: "An international law firm deployed contract analysis AI that cut due diligence time by 78 percent and opened up capacity for more deals.",
    challenge: "Every M&A transaction required six to twelve attorney weeks of manual contract review. It was a bottleneck that slowed deals and wore out associates.",
    solution: "We built a contract intelligence platform that reads, classifies and risk scores contract clauses automatically. Attorneys get a dashboard showing which clauses need attention rather than starting from page one every time.",
    outcomes: [{ metric: "78%", label: "Reduction in due diligence time" }, { metric: "4x", label: "Transaction capacity increase" }, { metric: "$2.8M", label: "New annual revenue from deal velocity" }, { metric: "99.4%", label: "Clause extraction accuracy" }],
    technologies: ["Claude API", "Python", "React", "PostgreSQL", "iManage"],
    duration: "6 months",
  },
  {
    slug: "beacon-university-admissions",
    image: "https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Beacon University Group",
    industry: "Education",
    title: "Transforming Admissions Across a Multi-Campus University",
    summary: "A university group with five campuses and 40,000 students cut admissions processing time by half and improved student outcomes by identifying at-risk learners earlier.",
    challenge: "Beacon's admissions team was processing over 80,000 applications a year using spreadsheets and email. Documents got lost, follow-ups were inconsistent and applicants were waiting weeks for responses. Once students enrolled, there was no system to flag who was struggling until it was often too late.",
    solution: "We built a unified admissions platform that automatically collects, classifies and scores applications, sends personalised communications at each stage and routes edge cases to the right staff member. We also deployed a student performance monitoring system that flags early warning signs so tutors can reach out before students fall too far behind.",
    outcomes: [{ metric: "50%", label: "Reduction in admissions processing time" }, { metric: "80K+", label: "Applications processed automatically per year" }, { metric: "34%", label: "Improvement in student retention rate" }, { metric: "4.8/5", label: "Applicant experience score" }],
    technologies: ["Next.js", "Python", "PostgreSQL", "OpenAI", "AWS", "Twilio"],
    duration: "10 months",
  },
  {
    slug: "premier-shield-insurance",
    image: "https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Premier Shield Insurance",
    industry: "Insurance",
    title: "AI Claims Processing That Cut Wait Times from Weeks to Hours",
    summary: "A mid-sized insurance company reduced claims processing time by 65 percent and dramatically improved customer satisfaction by automating its entire claims intake and triage operation.",
    challenge: "Premier Shield was receiving over 3,000 claims a month. Each one required a team member to manually read the submission, gather supporting documents, assess the claim and route it for approval. The average claim took 11 days to resolve. Customers were frustrated and staff were overwhelmed.",
    solution: "We built an end-to-end claims automation platform that reads incoming claims, extracts all relevant information, cross-references policy details, flags potential fraud indicators and routes each claim to the appropriate handler with a pre-populated summary. Straightforward claims are resolved automatically. Complex ones get to the right person faster with everything they need already prepared.",
    outcomes: [{ metric: "65%", label: "Faster claims resolution" }, { metric: "4 days", label: "Average resolution time, down from 11 days" }, { metric: "80%", label: "Reduction in fraudulent claims reaching payment" }, { metric: "$3.1M", label: "Annual operational savings" }],
    technologies: ["Python", "Claude API", "PostgreSQL", "Apache Kafka", "React", "AWS"],
    duration: "9 months",
  },
  {
    slug: "volta-manufacturing-maintenance",
    image: "https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Volta Manufacturing Group",
    industry: "Manufacturing",
    title: "Cutting Downtime by 35 Percent with Predictive Maintenance",
    summary: "A large industrial manufacturer eliminated most unplanned equipment failures and saved millions in lost production by deploying AI monitoring across its factory floor.",
    challenge: "Volta's factories were losing an average of 14 production days per year to unexpected equipment failures. When a machine broke down, it triggered a costly chain reaction of idle workers, delayed orders and emergency repair costs. The maintenance team was reactive by necessity because they had no way to see failures coming.",
    solution: "We installed sensor data collection across Volta's key production equipment and built a machine learning system that learns the normal operating patterns of each machine and detects early signs of failure days or weeks before a breakdown occurs. Maintenance teams now get prioritised alerts telling them exactly which equipment needs attention and when, so they can plan maintenance during scheduled downtime instead of scrambling during production hours.",
    outcomes: [{ metric: "35%", label: "Reduction in unplanned downtime" }, { metric: "14 days", label: "Production days recovered per year" }, { metric: "$6.8M", label: "Annual savings in repair and lost production costs" }, { metric: "3 weeks", label: "Average early warning before failure" }],
    technologies: ["Python", "TensorFlow", "Apache Kafka", "InfluxDB", "Grafana", "AWS IoT"],
    duration: "12 months",
  },
  {
    slug: "kente-retail-personalisation",
    image: "https://images.pexels.com/photos/5632388/pexels-photo-5632388.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Kente Retail Group",
    industry: "Retail and E-Commerce",
    title: "Personalisation at Scale for West Africa's Fastest Growing Retailer",
    summary: "One of West Africa's largest retail chains deployed AI personalisation and inventory intelligence across its online and physical stores, increasing revenue and cutting waste significantly.",
    challenge: "Kente had grown rapidly across Ghana, Nigeria and Ivory Coast but its systems had not kept up. Inventory decisions were being made by gut feel, leading to overstocked warehouses in some locations and empty shelves in others. Online customers were seeing the same generic experience regardless of their purchase history or location.",
    solution: "We built a unified commerce intelligence platform that connects Kente's online store, point of sale systems and warehouse data into a single view. The inventory system now forecasts demand at the store level and reorders automatically. The personalisation engine serves each online customer relevant products based on their behaviour, location and purchase patterns.",
    outcomes: [{ metric: "31%", label: "Reduction in overstock and stockout events" }, { metric: "22%", label: "Increase in average order value" }, { metric: "18%", label: "Overall revenue growth in first year" }, { metric: "40%", label: "Reduction in inventory waste" }],
    technologies: ["Next.js", "Python", "PostgreSQL", "Redis", "dbt", "Snowflake"],
    duration: "11 months",
  },
];

export const insights = [
  {
    slug: "enterprise-ai-readiness",
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Is Your Organisation Actually Ready for AI?",
    subtitle: "A practical framework for assessing where you stand before you commit to an AI programme",
    category: "Research",
    date: "January 2025",
    readTime: "12 min read",
    excerpt: "Most organisations approach AI the wrong way. They pick a use case, start building and then realise six months in that their data is a mess and their infrastructure cannot support what they are trying to do. There is a better way.",
    body: ["Most organisations approach AI the wrong way. They find an exciting use case, hire some engineers and start building. Six months later they realise their data quality is terrible, their systems cannot talk to each other and what they thought would take three months will take two years.", "The smarter approach is to assess your readiness before you commit. This means looking honestly at five areas: your data infrastructure, your compute capability, your governance frameworks, your team skills and your strategic alignment.", "Data infrastructure is where most organisations fall short. AI needs clean, well organised, accessible data. If your information is sitting in silos, inconsistently labelled or locked behind systems that do not talk to each other, you have homework to do before you start building models.", "Governance often gets ignored until something goes wrong. You need clear policies about how AI makes decisions, who reviews those decisions and what happens when the system gets something wrong. Building this in from the start is much easier than retrofitting it later.", "The organisations that get AI right share one thing in common. They treat it as an operational discipline, not a technology project. They invest in foundations before they chase results."],
  },
  {
    slug: "compliance-ai-finance",
    image: "https://images.pexels.com/photos/534216/pexels-photo-534216.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "How Banks Are Using AI to Handle Compliance",
    subtitle: "What is working, what is not and where the real opportunities are",
    category: "Industry Analysis",
    date: "December 2024",
    readTime: "9 min read",
    excerpt: "Regulatory requirements keep growing but compliance teams are not growing at the same pace. AI is changing how leading institutions handle this problem, and the results are significant.",
    body: ["Regulatory requirements for financial institutions have grown substantially over the past decade. The traditional response has been to hire more compliance staff and add more manual reviews. That approach has a ceiling.", "AI offers a different model. Instead of adding people to review more things, you build systems that monitor everything continuously and only surface the cases that genuinely need a human decision.", "Transaction monitoring is the most mature application. Modern AI systems can screen every transaction in real time, applying thousands of rules simultaneously. The volume of alerts goes up but the proportion that are genuine improves dramatically.", "Document intensive processes like KYC and regulatory reporting are also changing fast. Systems that can read, understand and validate complex documents are cutting review times from days to hours.", "The compliance function is shifting from reactive to proactive. Institutions with strong compliance AI can move faster, enter new markets with more confidence and spend less time managing regulatory relationships."],
  },
  {
    slug: "data-infrastructure-2025",
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Why AI Programmes Fail at the Data Layer",
    subtitle: "The infrastructure problems that derail most enterprise AI projects and how to avoid them",
    category: "Technology",
    date: "November 2024",
    readTime: "10 min read",
    excerpt: "The most common reason enterprise AI fails has nothing to do with the AI itself. It is the data underneath it. Here is what to look for.",
    body: ["The most common failure mode in enterprise AI is not a bad model. It is bad data. Organisations invest heavily in AI capabilities without first fixing the data problems that will undermine those capabilities from day one.", "Good data infrastructure has three layers. Collection and ingestion, which is how data gets into your systems. Storage and transformation, which is how it gets organised and made useful. And access and governance, which is how people and systems can use it safely.", "Collection is harder than it looks. Most enterprises have dozens of data sources with different formats, update frequencies and quality levels. Building reliable ingestion from all of them takes real engineering effort.", "Storage has improved dramatically in recent years. Modern data warehouses combined with transformation tools make it much easier to build clean, queryable data models. The challenge is maintaining discipline as the organisation grows.", "Governance is the layer most organisations neglect. Data that cannot be trusted because nobody is sure where it came from or whether it is current creates as many problems as having no data at all.", "Organisations that invest in these foundations before building AI find that each new use case is faster and cheaper than the last. The infrastructure pays dividends over time."],
  },
  {
    slug: "future-of-enterprise-agents",
    image: "https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "AI Agents Are Moving from Demo to Production",
    subtitle: "What it means for enterprise operations when AI can plan, act and coordinate on its own",
    category: "Perspective",
    date: "October 2024",
    readTime: "15 min read",
    excerpt: "The first wave of enterprise AI was mostly about answering questions and drafting content. The next wave is about systems that actually do things. That shift is closer than most organisations realise.",
    body: ["The first wave of enterprise AI was largely reactive. Chatbots that answered questions. Tools that drafted emails. Copilots that suggested code. These things delivered value but they still required a human to drive.", "The next wave is different. AI agents can set goals, make plans, use tools and take action across enterprise systems with minimal oversight. They can book meetings, process applications, write and execute code and coordinate with other agents.", "This is not science fiction. Organisations are already deploying agents in production for specific, well defined tasks. Customer onboarding, IT ticket resolution, contract review workflows. The results are promising.", "The main constraint right now is reliability. Agents make mistakes and in enterprise environments mistakes can have real consequences. The best deployments build in careful human oversight for high stakes decisions while letting agents run freely on routine ones.", "Over the next two to three years we expect to see multi-agent systems handling end to end business processes with minimal human involvement. The organisations building that capability now will have a meaningful head start."],
  },
  {
    slug: "ai-in-healthcare-operations",
    image: "https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "The Operational AI Opportunity in Healthcare",
    subtitle: "Clinical AI gets all the attention. The administrative opportunity might be bigger.",
    category: "Industry Analysis",
    date: "September 2024",
    readTime: "8 min read",
    excerpt: "Everyone talks about AI diagnosing diseases. But the more immediate and capturable opportunity in healthcare is on the administrative side, and it is enormous.",
    body: ["The healthcare AI conversation is dominated by clinical applications. AI that helps diagnose cancer, predict patient deterioration, discover new drugs. These are genuinely exciting and important.", "But the near term opportunity that is getting less attention is operational. Healthcare organisations spend an enormous amount of time and money on administrative work. Documentation, billing, prior authorisations, scheduling, compliance. Most of it is still largely manual.", "Clinical documentation alone represents a significant burden. Physicians in many health systems spend as much time documenting care as they spend delivering it. AI that can handle this work automatically has a direct impact on patient access and physician wellbeing.", "Revenue cycle management is another area where AI can make a meaningful difference. Claim denials, billing errors and slow collections cost healthcare organisations billions of dollars a year. A lot of this is addressable with better automation.", "The organisations moving fastest on operational AI in healthcare are finding that the ROI is strong and the implementation is relatively straightforward compared to clinical applications. It is a good place to start."],
  },
];

export const teamMembers = [
  {
    name: "Lawrencia Peasah Yeboah",
    title: "Founder",
    bio: "Lawrencia co-founded Coratech AI with a vision to bring world-class artificial intelligence and digital infrastructure to businesses across Africa and beyond. She leads the company's strategic direction and client relationships, combining deep technology knowledge with a passion for building systems that genuinely make organisations work better.",
    photo: "/lawrencia.png",
  },
  {
    name: "Ernest Kwame Adjei",
    title: "Founder",
    bio: "Ernest co-founded Coratech AI and leads its technology and product development. With extensive experience building enterprise software and AI systems, he brings the technical rigour and engineering discipline that underpins everything Coratech delivers. He believes great technology should be invisible — it should just work.",
    photo: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
];

export const values = [
  { title: "Precision over speed", description: "We build things that work correctly. Enterprise environments cannot absorb the cost of shortcuts and neither can we." },
  { title: "Long term relationships", description: "Our best work happens over time. We invest in understanding our clients deeply and design systems that get more valuable the longer they run." },
  { title: "Honest advice", description: "We tell clients what we actually think, not what they want to hear. Our independence is one of the most valuable things we offer." },
  { title: "Design matters", description: "Every system we build should be clear, easy to navigate and dignified to use. Complexity is a design failure." },
  { title: "AI that helps people", description: "We build AI that makes people more capable, not AI that replaces human responsibility. The distinction matters a lot." },
  { title: "Quality built in", description: "Quality is not something we check at the end. It is embedded in how we work, from the first architecture decision to the final deployment." },
];