export const solutions = [
  {
    slug: "ai-automation",
    title: "AI Automation",
    tagline: "Cut the manual work. Keep the quality.",
    icon: "⬡",
    description: "We help organisations stop spending time on repetitive tasks. Our automation systems handle document processing, approvals, data entry and routing so your team can focus on work that actually needs them.",
    capabilities: ["Document reading and data extraction", "Workflow routing and approvals", "Multi-system data synchronisation", "Automated reporting and alerts", "Human review for edge cases", "Process monitoring and analytics"],
    technologies: ["Python", "Apache Airflow", "OpenAI", "LangChain", "Kubernetes", "PostgreSQL"],
    industries: ["Finance", "Healthcare", "Legal", "Logistics"],
    benefits: [{ metric: "70%", label: "Less time spent on manual tasks" }, { metric: "99.2%", label: "Data extraction accuracy" }, { metric: "3x", label: "Throughput increase" }],
  },
  {
    slug: "ai-agents",
    title: "AI Agents",
    tagline: "AI that works on its own, around the clock.",
    icon: "◈",
    description: "Our AI agents can plan, reason and take action across your systems without needing someone to hold their hand. They handle complex tasks end to end, escalating only when human judgment is genuinely needed.",
    capabilities: ["Multi-agent task coordination", "Tool use and API integration", "Memory and context between sessions", "Goal planning and execution", "Live monitoring and control", "Custom agent training for your domain"],
    technologies: ["LangGraph", "AutoGen", "OpenAI", "Claude API", "Redis", "PostgreSQL"],
    industries: ["Technology", "Finance", "E-Commerce"],
    benefits: [{ metric: "24/7", label: "Autonomous operation" }, { metric: "85%", label: "Tasks completed without review" }, { metric: "60%", label: "Cost savings vs manual teams" }],
  },
  {
    slug: "enterprise-software",
    title: "Enterprise Software",
    tagline: "Software that lasts and scales.",
    icon: "▣",
    description: "We build software for organisations that need things to work reliably over the long term. No shortcuts, no duct tape. Just well-architected systems that hold up under real operational pressure.",
    capabilities: ["Full-stack application development", "Microservices and API design", "Database architecture", "Legacy system modernisation", "Cloud deployment and DevOps", "Performance and security hardening"],
    technologies: ["Next.js", "Node.js", "Go", "PostgreSQL", "AWS", "Docker"],
    industries: ["Government", "Finance", "Healthcare", "Technology"],
    benefits: [{ metric: "99.99%", label: "Uptime achieved for clients" }, { metric: "5x", label: "Faster release cycles" }, { metric: "40%", label: "Infrastructure cost reduction" }],
  },
  {
    slug: "data-intelligence",
    title: "Data Intelligence",
    tagline: "Your data should answer questions, not create them.",
    icon: "◉",
    description: "We build data systems that actually make sense of your information. Pipelines that run reliably, dashboards that tell you what matters, and models that help you make better decisions faster.",
    capabilities: ["Data warehouse design", "Real-time analytics pipelines", "Business intelligence dashboards", "Forecasting and predictive models", "Data quality and governance", "Self-service reporting tools"],
    technologies: ["dbt", "Snowflake", "Apache Kafka", "Databricks", "Tableau", "Metabase"],
    industries: ["Finance", "Healthcare", "E-Commerce", "Logistics"],
    benefits: [{ metric: "10x", label: "Faster insight generation" }, { metric: "98%", label: "Pipeline reliability" }, { metric: "60%", label: "Less time on reporting" }],
  },
  {
    slug: "compliance-systems",
    title: "Compliance Systems",
    tagline: "Stay on the right side of every regulation.",
    icon: "⬟",
    description: "Compliance work is getting harder and more expensive every year. We build systems that monitor, track and report on your regulatory obligations automatically, so your team spends less time on checklists and more time on strategy.",
    capabilities: ["Regulatory monitoring and alerts", "Audit trail management", "KYC and AML workflow automation", "GDPR and data privacy tools", "Risk scoring and reporting", "Regulatory change tracking"],
    technologies: ["Python", "Elasticsearch", "PostgreSQL", "Apache Kafka", "AWS GovCloud", "Vault"],
    industries: ["Finance", "Legal", "Healthcare", "Government"],
    benefits: [{ metric: "90%", label: "Less compliance review time" }, { metric: "Zero", label: "Regulatory violations post-launch" }, { metric: "75%", label: "Audit preparation time saved" }],
  },
  {
    slug: "cloud-infrastructure",
    title: "Cloud Infrastructure",
    tagline: "Infrastructure that runs quietly and costs less.",
    icon: "◻",
    description: "We design and manage cloud environments built for AI workloads, high availability and global scale. Whether you are migrating, modernising or building from scratch, we make sure the foundation is solid.",
    capabilities: ["Multi-cloud and hybrid architecture", "Infrastructure as code", "AI and ML compute management", "Security hardening and compliance", "Cost optimisation and FinOps", "Disaster recovery planning"],
    technologies: ["AWS", "GCP", "Azure", "Terraform", "Kubernetes", "Prometheus"],
    industries: ["Technology", "Finance", "Healthcare", "Government"],
    benefits: [{ metric: "40%", label: "Average infrastructure cost reduction" }, { metric: "99.99%", label: "Uptime achieved" }, { metric: "10x", label: "Faster deployment frequency" }],
  },
  {
    slug: "digital-transformation",
    title: "Digital Transformation",
    tagline: "Modernisation that actually sticks.",
    icon: "◆",
    description: "Most transformation programmes fail because they focus on technology and forget about people. We work with your teams from day one to make sure the change lands properly and delivers lasting results.",
    capabilities: ["Technology readiness assessment", "Roadmap and architecture planning", "Change management programmes", "Legacy migration strategy", "Vendor and platform selection", "Enterprise architecture consulting"],
    technologies: ["AWS", "Azure", "SAP", "Salesforce", "ServiceNow", "MuleSoft"],
    industries: ["Finance", "Healthcare", "Government", "Logistics", "Real Estate"],
    benefits: [{ metric: "2.5x", label: "ROI on transformation programmes" }, { metric: "83%", label: "Employee adoption rate" }, { metric: "18mo", label: "Average time to measurable impact" }],
  },
];

export const industries = [
  {
    slug: "finance",
    image: "https://images.pexels.com/photos/7876051/pexels-photo-7876051.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Financial Services",
    subtitle: "Built for the demands of a regulated industry.",
    description: "Financial institutions deal with enormous complexity every day. Regulatory pressure, real-time transaction requirements, fraud risk and the expectation of zero downtime. We have built systems for organisations in this space and we understand what is at stake.",
    challenges: ["Growing compliance burden across multiple jurisdictions", "Fraud detection that needs to work in real time", "Data sitting in silos across different business units", "Manual reporting consuming analyst capacity", "Legacy systems slowing down digital products"],
    solutions: ["Automated KYC and AML workflows", "Real-time fraud scoring and transaction monitoring", "Unified data platforms across business units", "Regulatory reporting automation", "Core banking modernisation and API layers"],
    stats: [{ metric: "99.8%", label: "Fraud detection accuracy" }, { metric: "$2.1B+", label: "Transactions processed daily" }, { metric: "85%", label: "Compliance review time reduced" }],
  },
  {
    slug: "healthcare",
    image: "https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Healthcare",
    subtitle: "Technology that serves patients as much as staff.",
    description: "Healthcare organisations need technology that is both innovative and rigorously safe. Every system we build for this sector is designed around clinical requirements, data privacy and regulatory compliance. Patient outcomes come first.",
    challenges: ["Documentation burden reducing time with patients", "HIPAA compliance across complex data ecosystems", "Poor interoperability between legacy systems", "Diagnostic support and triage at scale", "Revenue cycle inefficiency and claims errors"],
    solutions: ["Clinical documentation AI and ambient transcription", "HIPAA compliant data infrastructure", "Healthcare interoperability using HL7 FHIR", "AI assisted clinical decision support", "Automated revenue cycle management"],
    stats: [{ metric: "40%", label: "Reduction in documentation time" }, { metric: "100%", label: "HIPAA compliance maintained" }, { metric: "3x", label: "Faster claims processing" }],
  },
  {
    slug: "legal",
    image: "https://images.pexels.com/photos/5669619/pexels-photo-5669619.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Legal Services",
    subtitle: "AI that works alongside attorneys, not instead of them.",
    description: "Legal work demands precision. We build tools that help law firms and legal teams handle large document volumes, speed up research and manage contracts without cutting corners on accuracy.",
    challenges: ["Document review and due diligence taking weeks", "Research time eating into billable capacity", "Contract management across large portfolios", "Knowledge that walks out the door with people", "Client reporting taking too long"],
    solutions: ["AI powered contract analysis and review", "Legal research with citation verification", "Contract lifecycle management systems", "Knowledge base and precedent search", "Matter management and client dashboards"],
    stats: [{ metric: "75%", label: "Reduction in document review time" }, { metric: "10x", label: "Research throughput increase" }, { metric: "$180K", label: "Annual savings per attorney" }],
  },
  {
    slug: "logistics",
    image: "https://images.pexels.com/photos/1427541/pexels-photo-1427541.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Logistics and Supply Chain",
    subtitle: "Intelligence for operations that never stop.",
    description: "Global supply chains run at a pace that leaves no room for guesswork. We build the intelligence layer that helps logistics organisations forecast demand, optimise routes and keep goods moving reliably.",
    challenges: ["Demand forecasting accuracy and inventory costs", "Last mile delivery efficiency", "Supplier visibility and risk exposure", "Customs and cross border compliance", "Warehouse operations and labour planning"],
    solutions: ["AI powered demand forecasting", "Route optimisation systems", "Supplier risk monitoring", "Customs documentation automation", "Warehouse management and robotics integration"],
    stats: [{ metric: "23%", label: "Inventory cost reduction" }, { metric: "15%", label: "Delivery efficiency improvement" }, { metric: "99.1%", label: "On time delivery rate" }],
  },
  {
    slug: "real-estate",
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Real Estate",
    subtitle: "Smarter tools for asset heavy organisations.",
    description: "Real estate organisations manage complex portfolios, high volume transactions and a lot of stakeholder relationships. We build platforms that bring clarity to every stage of the property lifecycle.",
    challenges: ["Property valuation accuracy", "Transaction and document management", "Tenant experience and service delivery", "Portfolio performance reporting", "Compliance across multiple jurisdictions"],
    solutions: ["AI powered property valuation and market analytics", "Transaction management and document automation", "Tenant experience portals", "Portfolio management dashboards", "Compliance monitoring systems"],
    stats: [{ metric: "94%", label: "Valuation model accuracy" }, { metric: "60%", label: "Faster transaction processing" }, { metric: "4.8/5", label: "Tenant satisfaction score" }],
  },
  {
    slug: "government",
    image: "https://images.pexels.com/photos/1550337/pexels-photo-1550337.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Government and Public Sector",
    subtitle: "Systems that serve the public well.",
    description: "Government agencies operate under unique constraints. Security requirements, public accountability and the need to serve everyone fairly. We build systems that meet these requirements without sacrificing usability.",
    challenges: ["Legacy infrastructure that is hard to replace", "Citizen services that need to work at scale", "Security and data sovereignty requirements", "Cross agency collaboration and data sharing", "Procurement and delivery complexity"],
    solutions: ["Secure cloud modernisation with compliance built in", "Citizen portal development", "Identity and access management", "Interagency data sharing platforms", "AI powered service routing and support"],
    stats: [{ metric: "99.99%", label: "System uptime achieved" }, { metric: "5M+", label: "Citizens served via our systems" }, { metric: "70%", label: "Faster permit and service processing" }],
  },
  {
    slug: "education",
    image: "https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Education",
    subtitle: "Technology that helps institutions focus on learning.",
    description: "Educational institutions are under pressure to do more with less. Improve student outcomes, reduce administrative burden and adapt to an increasingly digital world. We build the systems that make that possible without losing the human element that makes education work.",
    challenges: ["Administrative work consuming teacher and staff time", "Student data scattered across disconnected systems", "Identifying at-risk students before they fall behind", "Inefficient enrolment and admissions processes", "Reporting and compliance across regulatory bodies"],
    solutions: ["Automated administrative and admissions workflows", "Unified student information platforms", "Early intervention and at-risk student detection", "AI powered learning analytics and reporting", "Compliance and accreditation management systems"],
    stats: [{ metric: "50%", label: "Reduction in administrative workload" }, { metric: "3x", label: "Faster admissions processing" }, { metric: "30%", label: "Improvement in student retention rates" }],
  },
  {
    slug: "manufacturing",
    image: "https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Manufacturing",
    subtitle: "AI that keeps production lines moving.",
    description: "Modern manufacturing runs on precision. A line that goes down costs thousands per hour. A defect that reaches a customer costs far more. We build intelligence systems that help manufacturers predict problems before they happen and optimise operations continuously.",
    challenges: ["Unplanned equipment downtime and maintenance costs", "Quality control and defect detection at speed", "Supply chain disruptions affecting production schedules", "Energy consumption and operational efficiency", "Workforce scheduling and labour optimisation"],
    solutions: ["Predictive maintenance and equipment monitoring", "AI powered visual quality inspection", "Supply chain visibility and disruption alerts", "Energy optimisation and production scheduling", "Workforce planning and shift management systems"],
    stats: [{ metric: "35%", label: "Reduction in unplanned downtime" }, { metric: "98.5%", label: "Defect detection accuracy" }, { metric: "20%", label: "Energy cost reduction" }],
  },
  {
    slug: "insurance",
    image: "https://images.pexels.com/photos/5900184/pexels-photo-5900184.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Insurance",
    subtitle: "Faster decisions, better risk management.",
    description: "Insurance is fundamentally a data business. The organisations that can assess risk accurately, process claims quickly and detect fraud reliably are the ones that grow profitably. We build the AI systems that make all three possible at scale.",
    challenges: ["Slow and manual claims processing frustrating customers", "Fraud costing billions across the industry every year", "Inaccurate risk assessment leading to poor pricing", "Regulatory compliance across multiple markets", "Legacy policy management systems blocking innovation"],
    solutions: ["Automated claims processing and triage", "AI fraud detection across claims and applications", "Risk scoring and actuarial modelling systems", "Regulatory reporting and compliance automation", "Policy management platform modernisation"],
    stats: [{ metric: "65%", label: "Faster claims processing" }, { metric: "89%", label: "Fraud detection accuracy" }, { metric: "42%", label: "Reduction in claims handling costs" }],
  },
  {
    slug: "retail",
    image: "https://images.pexels.com/photos/5632397/pexels-photo-5632397.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Retail and E-Commerce",
    subtitle: "AI that turns browsers into buyers and buyers into loyalists.",
    description: "Retail moves fast and margins are tight. The difference between a good year and a great one often comes down to getting the right product in the right place at the right time and giving customers an experience that keeps them coming back.",
    challenges: ["Inventory management and stockout prevention", "Personalisation at scale across large customer bases", "Demand forecasting accuracy across seasons and regions", "Returns management and reverse logistics", "Customer service volume and response times"],
    solutions: ["AI powered inventory and demand forecasting", "Personalised recommendation and marketing engines", "Customer service automation and chatbots", "Returns processing and fraud detection", "Omnichannel analytics and customer insights"],
    stats: [{ metric: "28%", label: "Increase in average order value" }, { metric: "45%", label: "Reduction in stockouts" }, { metric: "3.2x", label: "Customer lifetime value improvement" }],
  },
];

export const caseStudies = [
  {
    slug: "meridian-bank-compliance",
    image: "https://images.pexels.com/photos/7876051/pexels-photo-7876051.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Meridian Financial Group",
    industry: "Financial Services",
    title: "Rebuilding Compliance for a Global Bank",
    summary: "A global bank with $340 billion in assets needed to overhaul its compliance systems after regulators identified serious gaps in how it monitored transactions.",
    challenge: "Meridian's compliance team was using a mix of old tools, spreadsheets and manual reviews to manage obligations across 14 countries. When regulators examined them, they found it was taking up to 48 hours to flag suspicious transactions. That was not good enough.",
    solution: "We designed and built a compliance intelligence platform that monitors every transaction in real time, generates suspicious activity reports automatically and keeps a clean audit trail of everything. We connected it to their existing core banking system through a custom API layer, so nothing had to be ripped out.",
    outcomes: [{ metric: "2 hrs", label: "Average detection time, down from 48 hours" }, { metric: "91%", label: "Reduction in manual compliance tasks" }, { metric: "$4.2M", label: "Annual operational savings" }, { metric: "Zero", label: "Regulatory findings in follow up examinations" }],
    technologies: ["Python", "Apache Kafka", "Elasticsearch", "PostgreSQL", "AWS GovCloud"],
    duration: "14 months",
  },
  {
    slug: "atlas-health-documentation",
    image: "https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Atlas Health Network",
    industry: "Healthcare",
    title: "Giving Doctors Their Time Back",
    summary: "A regional health network with 47 hospitals deployed ambient AI documentation across its physician workforce and recovered thousands of hours of clinical capacity.",
    challenge: "Physicians at Atlas were spending over three hours per shift on documentation. That is time taken directly away from patients. Burnout was rising and the quality of notes was inconsistent, which was causing billing errors downstream.",
    solution: "We built a system that listens to physician patient conversations, generates structured clinical notes automatically and pushes them into their Epic records for review. Doctors check and approve, but they are not starting from scratch every time.",
    outcomes: [{ metric: "2.1 hrs", label: "Documentation time saved per physician per shift" }, { metric: "98.7%", label: "Documentation accuracy rate" }, { metric: "$28M", label: "Annual capacity value recovered" }, { metric: "4.7/5", label: "Physician satisfaction score" }],
    technologies: ["Whisper API", "GPT-4", "HL7 FHIR", "React", "AWS HIPAA"],
    duration: "8 months",
  },
  {
    slug: "nexus-logistics-forecasting",
    image: "https://images.pexels.com/photos/1427541/pexels-photo-1427541.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Nexus Global Logistics",
    industry: "Logistics",
    title: "Smarter Inventory Across 180 Distribution Centres",
    summary: "One of the world's largest logistics operators deployed AI forecasting that cut inventory holding costs by 23 percent while improving fulfilment rates.",
    challenge: "Nexus was making inventory decisions based on data that was 90 days old. They had 180 distribution centres and 3,400 clients. Overstock and stockouts were costing them $180 million a year.",
    solution: "We built a demand intelligence platform that pulls in over 240 signals including weather, economic data and client order history and updates inventory recommendations every four hours. Distribution managers see what they need to order before they run out.",
    outcomes: [{ metric: "23%", label: "Inventory cost reduction" }, { metric: "99.1%", label: "Order fulfilment rate" }, { metric: "$41M", label: "First year savings" }, { metric: "4 hours", label: "Forecast update frequency, down from 90 days" }],
    technologies: ["Python", "XGBoost", "Apache Kafka", "Snowflake", "dbt", "Kubernetes"],
    duration: "11 months",
  },
  {
    slug: "caldwell-legal-platform",
    image: "https://images.pexels.com/photos/5669619/pexels-photo-5669619.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Caldwell and Reyes LLP",
    industry: "Legal Services",
    title: "Faster Due Diligence for a 600 Attorney Firm",
    summary: "An international law firm deployed contract analysis AI that cut due diligence time by 78 percent and opened up capacity for more deals.",
    challenge: "Every M&A transaction required six to twelve attorney weeks of manual contract review. It was a bottleneck that slowed deals and wore out associates.",
    solution: "We built a contract intelligence platform that reads, classifies and risk scores contract clauses automatically. Attorneys get a dashboard showing which clauses need attention rather than starting from page one every time.",
    outcomes: [{ metric: "78%", label: "Reduction in due diligence time" }, { metric: "4x", label: "Transaction capacity increase" }, { metric: "$2.8M", label: "New annual revenue from deal velocity" }, { metric: "99.4%", label: "Clause extraction accuracy" }],
    technologies: ["Claude API", "Python", "React", "PostgreSQL", "iManage"],
    duration: "6 months",
  },
  {
    slug: "brightpath-education-platform",
    image: "https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Brightpath University Group",
    industry: "Education",
    title: "Cutting Admin in Half Across a 12 Campus University Group",
    summary: "A university group with 85,000 students deployed AI automation across admissions, student records and compliance reporting and freed up hundreds of staff hours every week.",
    challenge: "Brightpath's administrative teams were drowning. Admissions involved manually reviewing thousands of applications. Student records lived in four different systems that did not talk to each other. Compliance reports took two weeks to produce each quarter. Staff were working evenings and weekends just to keep up.",
    solution: "We built a unified student data platform that connected all four legacy systems through a single API layer. On top of that we deployed an admissions screening tool that reads and scores applications automatically, surfacing the strongest candidates for human review. Compliance reports now generate in minutes, not weeks.",
    outcomes: [{ metric: "50%", label: "Reduction in administrative workload across all campuses" }, { metric: "3x", label: "Faster admissions processing from application to decision" }, { metric: "12 mins", label: "Compliance report generation, down from two weeks" }, { metric: "94%", label: "Staff satisfaction with the new systems" }],
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Python", "AWS", "Salesforce"],
    duration: "10 months",
  },
  {
    slug: "vantage-insurance-claims",
    image: "https://images.pexels.com/photos/5900184/pexels-photo-5900184.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Vantage Insurance Group",
    industry: "Insurance",
    title: "Automated Claims Processing for a Regional Insurer",
    summary: "A regional insurance company processing 40,000 claims a month deployed AI automation that cut processing time by 65 percent and identified $3.8 million in fraudulent claims in the first year.",
    challenge: "Vantage had a claims backlog growing every month. Processing a single claim took an average of 11 days. Fraud was slipping through because investigators did not have time to look closely at every case. Customer complaints were increasing and the company was losing renewals as a result.",
    solution: "We built an end-to-end claims processing system that reads incoming documents, validates information against policy records, assesses fraud risk using behavioural pattern analysis and routes cases automatically. Straightforward claims close in hours. Suspicious ones are flagged with a detailed risk report for human investigators.",
    outcomes: [{ metric: "65%", label: "Reduction in claims processing time" }, { metric: "$3.8M", label: "Fraudulent claims identified in year one" }, { metric: "4.1 days", label: "Average claim resolution, down from 11 days" }, { metric: "38%", label: "Reduction in customer complaints" }],
    technologies: ["Python", "Claude API", "PostgreSQL", "Apache Kafka", "React", "AWS"],
    duration: "9 months",
  },
  {
    slug: "crestview-manufacturing-maintenance",
    image: "https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Crestview Industrial Group",
    industry: "Manufacturing",
    title: "Predictive Maintenance Across 6 Production Facilities",
    summary: "A mid-sized industrial manufacturer deployed AI-powered predictive maintenance across its facilities and cut unplanned downtime by 35 percent in the first six months.",
    challenge: "Crestview was losing an average of $180,000 per hour whenever a production line went down unexpectedly. Their maintenance approach was reactive. Equipment failed, teams scrambled to fix it, production halted. They knew predictive maintenance was the answer but had no way to get there with ageing equipment.",
    solution: "We fitted sensor arrays to 340 pieces of critical equipment across all six facilities and built a data pipeline to ingest readings in real time. A machine learning model trained on 18 months of historical failure data now monitors every machine continuously and raises alerts when patterns suggest a component is approaching failure.",
    outcomes: [{ metric: "35%", label: "Reduction in unplanned downtime within six months" }, { metric: "$12M", label: "Estimated annual savings from prevented failures" }, { metric: "340", label: "Machines monitored in real time" }, { metric: "21 days", label: "Average advance warning before predicted failures" }],
    technologies: ["Python", "TensorFlow", "Apache Kafka", "InfluxDB", "Grafana", "AWS IoT"],
    duration: "12 months",
  },
  {
    slug: "kora-retail-personalisation",
    image: "https://images.pexels.com/photos/5632397/pexels-photo-5632397.jpeg?auto=compress&cs=tinysrgb&w=800",
    client: "Kora Retail Group",
    industry: "Retail and E-Commerce",
    title: "Personalisation at Scale for a Pan-African Retailer",
    summary: "One of West Africa's largest retail chains deployed AI personalisation and demand forecasting across its channels, driving a 28 percent increase in average order value.",
    challenge: "Kora had 4.2 million active customers across Ghana, Nigeria and Senegal and almost no ability to treat them differently. Every customer received the same promotions and recommendations. Inventory decisions were made manually using last year's data. Stockouts were frequent and customers were leaving for competitors who felt more relevant.",
    solution: "We built a customer data platform that unified online and in-store purchase history, then layered a recommendation engine on top that personalises the homepage, email campaigns and promotions for every customer segment. Separately we built a demand forecasting system that generates store-level stock recommendations weekly.",
    outcomes: [{ metric: "28%", label: "Increase in average order value within three months" }, { metric: "45%", label: "Reduction in stockouts across all locations" }, { metric: "3.2x", label: "Improvement in email campaign conversion rates" }, { metric: "$6.1M", label: "Additional revenue attributed to personalisation in year one" }],
    technologies: ["Python", "Next.js", "PostgreSQL", "Apache Kafka", "dbt", "Snowflake"],
    duration: "8 months",
  },
];

export const insights = [
  {
    slug: "enterprise-ai-readiness",
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Is Your Organisation Actually Ready for AI?",
    subtitle: "A practical framework for assessing where you stand before you commit to an AI programme",
    category: "Research",
    date: "January 2025",
    readTime: "12 min read",
    excerpt: "Most organisations approach AI the wrong way. They pick a use case, start building and then realise six months in that their data is a mess and their infrastructure cannot support what they are trying to do. There is a better way.",
    body: ["Most organisations approach AI the wrong way. They find an exciting use case, hire some engineers and start building. Six months later they realise their data quality is terrible, their systems cannot talk to each other and what they thought would take three months will take two years.", "The smarter approach is to assess your readiness before you commit. This means looking honestly at five areas: your data infrastructure, your compute capability, your governance frameworks, your team skills and your strategic alignment.", "Data infrastructure is where most organisations fall short. AI needs clean, well organised, accessible data. If your information is sitting in silos, inconsistently labelled or locked behind systems that do not talk to each other, you have homework to do before you start building models.", "Governance often gets ignored until something goes wrong. You need clear policies about how AI makes decisions, who reviews those decisions and what happens when the system gets something wrong. Building this in from the start is much easier than retrofitting it later.", "The organisations that get AI right share one thing in common. They treat it as an operational discipline, not a technology project. They invest in foundations before they chase results."],
  },
  {
    slug: "compliance-ai-finance",
    image: "https://images.pexels.com/photos/7876051/pexels-photo-7876051.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "How Banks Are Using AI to Handle Compliance",
    subtitle: "What is working, what is not and where the real opportunities are",
    category: "Industry Analysis",
    date: "December 2024",
    readTime: "9 min read",
    excerpt: "Regulatory requirements keep growing but compliance teams are not growing at the same pace. AI is changing how leading institutions handle this problem, and the results are significant.",
    body: ["Regulatory requirements for financial institutions have grown substantially over the past decade. The traditional response has been to hire more compliance staff and add more manual reviews. That approach has a ceiling.", "AI offers a different model. Instead of adding people to review more things, you build systems that monitor everything continuously and only surface the cases that genuinely need a human decision.", "Transaction monitoring is the most mature application. Modern AI systems can screen every transaction in real time, applying thousands of rules simultaneously. The volume of alerts goes up but the proportion that are genuine improves dramatically.", "Document intensive processes like KYC and regulatory reporting are also changing fast. Systems that can read, understand and validate complex documents are cutting review times from days to hours.", "The compliance function is shifting from reactive to proactive. Institutions with strong compliance AI can move faster, enter new markets with more confidence and spend less time managing regulatory relationships."],
  },
  {
    slug: "data-infrastructure-2025",
    image: "https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "Why AI Programmes Fail at the Data Layer",
    subtitle: "The infrastructure problems that derail most enterprise AI projects and how to avoid them",
    category: "Technology",
    date: "November 2024",
    readTime: "10 min read",
    excerpt: "The most common reason enterprise AI fails has nothing to do with the AI itself. It is the data underneath it. Here is what to look for.",
    body: ["The most common failure mode in enterprise AI is not a bad model. It is bad data. Organisations invest heavily in AI capabilities without first fixing the data problems that will undermine those capabilities from day one.", "Good data infrastructure has three layers. Collection and ingestion, which is how data gets into your systems. Storage and transformation, which is how it gets organised and made useful. And access and governance, which is how people and systems can use it safely.", "Collection is harder than it looks. Most enterprises have dozens of data sources with different formats, update frequencies and quality levels. Building reliable ingestion from all of them takes real engineering effort.", "Storage has improved dramatically in recent years. Modern data warehouses combined with transformation tools make it much easier to build clean, queryable data models. The challenge is maintaining discipline as the organisation grows.", "Governance is the layer most organisations neglect. Data that cannot be trusted because nobody is sure where it came from or whether it is current creates as many problems as having no data at all.", "Organisations that invest in these foundations before building AI find that each new use case is faster and cheaper than the last. The infrastructure pays dividends over time."],
  },
  {
    slug: "future-of-enterprise-agents",
    image: "https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "AI Agents Are Moving from Demo to Production",
    subtitle: "What it means for enterprise operations when AI can plan, act and coordinate on its own",
    category: "Perspective",
    date: "October 2024",
    readTime: "15 min read",
    excerpt: "The first wave of enterprise AI was mostly about answering questions and drafting content. The next wave is about systems that actually do things. That shift is closer than most organisations realise.",
    body: ["The first wave of enterprise AI was largely reactive. Chatbots that answered questions. Tools that drafted emails. Copilots that suggested code. These things delivered value but they still required a human to drive.", "The next wave is different. AI agents can set goals, make plans, use tools and take action across enterprise systems with minimal oversight. They can book meetings, process applications, write and execute code and coordinate with other agents.", "This is not science fiction. Organisations are already deploying agents in production for specific, well defined tasks. Customer onboarding, IT ticket resolution, contract review workflows. The results are promising.", "The main constraint right now is reliability. Agents make mistakes and in enterprise environments mistakes can have real consequences. The best deployments build in careful human oversight for high stakes decisions while letting agents run freely on routine ones.", "Over the next two to three years we expect to see multi-agent systems handling end to end business processes with minimal human involvement. The organisations building that capability now will have a meaningful head start."],
  },
  {
    slug: "ai-in-healthcare-operations",
    image: "https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&w=800",
    title: "The Operational AI Opportunity in Healthcare",
    subtitle: "Clinical AI gets all the attention. The administrative opportunity might be bigger.",
    category: "Industry Analysis",
    date: "September 2024",
    readTime: "8 min read",
    excerpt: "Everyone talks about AI diagnosing diseases. But the more immediate and capturable opportunity in healthcare is on the administrative side, and it is enormous.",
    body: ["The healthcare AI conversation is dominated by clinical applications. AI that helps diagnose cancer, predict patient deterioration, discover new drugs. These are genuinely exciting and important.", "But the near term opportunity that is getting less attention is operational. Healthcare organisations spend an enormous amount of time and money on administrative work. Documentation, billing, prior authorisations, scheduling, compliance. Most of it is still largely manual.", "Clinical documentation alone represents a significant burden. Physicians in many health systems spend as much time documenting care as they spend delivering it. AI that can handle this work automatically has a direct impact on patient access and physician wellbeing.", "Revenue cycle management is another area where AI can make a meaningful difference. Claim denials, billing errors and slow collections cost healthcare organisations billions of dollars a year. A lot of this is addressable with better automation.", "The organisations moving fastest on operational AI in healthcare are finding that the ROI is strong and the implementation is relatively straightforward compared to clinical applications. It is a good place to start."],
  },
];

export const teamMembers = [
  {
    name: "Lawrencia Peasah Yeboah",
    title: "Founder",
    bio: "Lawrencia co-founded Coratech AI with a vision to bring world-class artificial intelligence and digital infrastructure to businesses across Africa and beyond. She leads the company's strategic direction and client relationships, combining deep technology knowledge with a passion for building systems that genuinely make organisations work better.",
    photo: "/lawrencia.png",
  },
  {
    name: "Ernest Kwame Adjei",
    title: "Founder",
    bio: "Ernest co-founded Coratech AI and leads its technology and product development. With extensive experience building enterprise software and AI systems, he brings the technical rigour and engineering discipline that underpins everything Coratech delivers. He believes great technology should be invisible — it should just work.",
    photo: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
];

export const values = [
  { title: "Precision over speed", description: "We build things that work correctly. Enterprise environments cannot absorb the cost of shortcuts and neither can we." },
  { title: "Long term relationships", description: "Our best work happens over time. We invest in understanding our clients deeply and design systems that get more valuable the longer they run." },
  { title: "Honest advice", description: "We tell clients what we actually think, not what they want to hear. Our independence is one of the most valuable things we offer." },
  { title: "Design matters", description: "Every system we build should be clear, easy to navigate and dignified to use. Complexity is a design failure." },
  { title: "AI that helps people", description: "We build AI that makes people more capable, not AI that replaces human responsibility. The distinction matters a lot." },
  { title: "Quality built in", description: "Quality is not something we check at the end. It is embedded in how we work, from the first architecture decision to the final deployment." },
];
// This will be replaced - just checking file exists
